version: "3.9"

services:

  # ------------------ PROMETHEUS ------------------
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ------------------ GRAFANA ------------------
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - jaeger

  # ------------------ LOKI ------------------
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # ------------------ PROMTAIL ------------------
  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./observability/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  # ------------------ KAFKA EXPORTER ------------------
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=host.docker.internal:9092"
      - "--log.level=info"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ------------------ ALERTMANAGER ------------------
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/config.yml

  # ------------------ HEALING SERVICE ------------------
  healing-service:
    build: ./healing_service
    container_name: healing-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=host.docker.internal
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
      - alertmanager

  # ------------------ JAEGER ------------------
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP HTTP
      - "4317:4317"     # OTLP gRPC
